name: Test mdformat

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Test mdformat
    runs-on: ubuntu-latest
    steps:
      - install-deps:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
        
      - run-tests:
          name: run tests
          command: |
            . env/bin/activate
            pytest -vvx markdown_helpers/tables.py 
