name: Test mdformat

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Test mdformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python3 -m venv env
          . env/bin/activate
          pip install -r requirements.txt
        
      - name: run tests
        run: |
          . env/bin/activate
          pytest -vvx markdown_helpers/tables.py 
